# Global Configs
[config]
version_check = false

# Templates

# Waybar
[templates.waybar]
input_path = '~/.config/matugen/templates/matugen-waybar.css'
output_path = '~/.config/waybar/matugen/matugen-waybar.css'
post_hook = 'pkill -SIGUSR2 waybar'

# Hyprland
[templates.hyprland]
input_path = '~/.config/matugen/templates/matugen-hyprland.conf'
output_path = '~/.config/hypr/matugen/matugen-hyprland.conf'
post_hook = 'hyprctl reload'

# Kitty
[templates.kitty]
input_path = '~/.config/matugen/templates/matugen-kitty.conf'
output_path = '~/.config/kitty/matugen/matugen-colors.conf'

# Kvantum
[templates.kvantum]
input_path = '~/.config/matugen/templates/matugen.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

# Qt5
[templates.qt5]
input_path = '~/.config/matugen/templates/matugen-qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen-qt5ct.conf'

# Qt6
[templates.qt6]
input_path = '~/.config/matugen/templates/matugen-qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen-qt6ct.conf'

# Rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/matugen-rofi.rasi'
output_path = '~/.config/rofi/matugen/matugen-rofi.rasi'

# Swaync
[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync.css'
output_path = '~/.config/swaync/matugen/matugen-swaync.css'
post_hook = 'swaync-client -rs'