# Global Configs
[config]
version_check = false

# Templates

# Waybar
[templates.waybar]
input_path = '~/.config/matugen/templates/matugen-waybar.css'
output_path = '~/.config/waybar/matugen/matugen-waybar.css'
post_hook = 'pkill -SIGUSR2 waybar'

# Hyprland
[templates.hyprland]
input_path = '~/.config/matugen/templates/matugen-hyprland.conf'
output_path = '~/.config/hypr/matugen/matugen-hyprland.conf'
post_hook = 'hyprctl reload'

# Kitty
[templates.kitty]
input_path = '~/.config/matugen/templates/matugen-kitty.conf'
output_path = '~/.config/kitty/matugen/matugen-colors.conf'

# Rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/matugen-rofi.rasi'
output_path = '~/.config/rofi/matugen/matugen-rofi.rasi'